alias ga="git add"
alias gaa="git add --all"
alias gac='git add -A && git commit -m'
alias gcm='git commit -m'
alias gp='git push'
alias gss='git status -sb'
alias gl="git pull"
alias gb="git branch"
alias gcb="git checkout -b"
alias gco="git checkout"
alias web='cd ~/work/canva/web'
